export const gikiToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwOGRiMTkyLWNhYjEtNDc5ZS04ZmNjLWY2MmY1OTBlOTFiOSIsIm5hbWUiOiJxaSIsInByb3ZpZGVyIjoiZ2l0aHViIiwicHJvdmlkZXJVc2VySWQiOjIyNzcyODMwLCJpYXQiOjE2MDM4Nzk2MDgsImV4cCI6MTYwNjQ3MTYwOH0.KqU5lUodM4u1VTuEze-aUz7zoxKnjRNkbdGnILQ229g";
export const userName = "qi";
